name: gpn
channels:
  - pytorch
  - conda-forge
  - defaults
  - pyg
  - anaconda
dependencies:
  - cudatoolkit
  - _libgcc_mutex=0.1
  - argon2-cffi=20.1.0
  - astroid=2.4.2
  - async_generator=1.10
  - attrs=20.2.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - blinker=1.4
  - bravado=11.0.1
  - bravado-core=5.17.0
  - brotlipy=0.7.0
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cffi=1.14.3
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=3.1.1
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.10
  - filelock=3.0.12
  - fontconfig=2.13.0
  - freetype=2.10.3
  - future=0.18.2
  - gitdb=4.0.5
  - gitpython=3.1.9
  - glib=2.66.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0=1
  - intel-openmp
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=5.6.4
  - jedi=0.17.2
  - jinja2=2.11.2
  - joblib=0.17.0
  - jpeg=9b
  - jsonref=0.2
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.6.3
  - jupyterlab_pygments=0.1.2
  - lazy-object-proxy=1.4.3
  - lcms2=2.11
  - ld_impl_linux-64
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran-ng
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib-base=3.2.2
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - monotonic=1.5
  - msgpack-python=1.0.0
  - nbclient=0.5.0
  - nbconvert=6.0.7
  - nbformat=5.0.7
  - ncurses=6.2
  - nest-asyncio=1.4.1
  - ninja=1.10.1
  - notebook=6.1.4
  - oauthlib=3.1.0
  - olefile=0.46
  - openssl=1.1.1l
  - packaging=20.4
  - pandas=1.1.3
  - pandoc=2.11
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.2.3
  - plotly=4.14.3
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8=0
  - ptyprocess=0.6.0
  - py3nvml=0.2.5
  - pycparser=2.20
  - pygments=2.7.1
  - pyjwt=1.7.1
  - pylint=2.6.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.3
  - python-dateutil=2.8.1
  - python_abi=3.8=1_cp38
  - pytorch=1.10.0
  - pytorch-cluster=1.5.9
  - pyg
  - pytorch-sparse=0.6.12
  - pytorch-scatter=2.0.9
  - pytorch-spline-conv=1.2.1
  - pytz=2020.1
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - qt=5.9.7
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - readline=8.0
  - requests=2.24.0
  - requests-oauthlib=1.3.0
  - retrying=1.3.3
  - rope=0.18.0
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.0
  - send2trash=1.5.0
  - setuptools=50.3.0
  - simplejson=3.17.2
  - sip=4.19.13
  - six=1.15.0
  - smmap=3.0.4
  - sqlite=3.33.0
  - swagger-spec-validator=2.7.3
  - terminado=0.9.1
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.1
  - torchvision=0.11.1
  - tornado=6.0.4
  - traitlets=5.0.4
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3
  - urllib3=1.25.10
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - xmltodict=0.12.0
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.3
  - zipp=3.3.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
      - absl-py==0.10.0
      - ase==3.20.1
      - astunparse==1.6.3
      - attrdict==2.0.1
      - cachetools==4.1.1
      - cloudpickle==1.6.0
      - colorama==0.4.4
      - cycler==0.10.0
      - dataclasses==0.6
      - debugpy==1.3.0
      - deprecated==1.2.12
      - dm-tree==0.1.6
      - docopt==0.6.2
      - flatbuffers==1.12
      - gast==0.3.3
      - google-auth==1.22.1
      - google-auth-oauthlib==0.4.1
      - google-pasta==0.2.0
      - googledrivedownloader==0.4
      - gpflow==2.2.1
      - grpcio==1.32.0
      - h5py==2.10.0
      - isodate==0.6.0
      - jsonpickle==1.4.1
      - jsonpointer==2.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.2.0
      - littleutils==0.2.2
      - llvmlite==0.31.0
      - markdown==3.3.2
      - matplotlib==3.4.2
      - mccabe==0.6.1
      - mplcursors==0.4
      - multipledispatch==0.6.0
      - munch==2.5.0
      - networkx==2.5
      - numba==0.48.0
      - numpy==1.19.5
      - ogb==1.3.1
      - opt-einsum==3.3.0
      - outdated==0.2.1
      - protobuf==3.13.0
      - psutil==5.7.2
      - py-cpuinfo==7.0.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pyblaze==2.3.1
      - pymongo==3.11.0
      - pyro-api==0.1.2
      - pyro-ppl==1.5.0
      - python-louvain==0.15
      - rdflib==5.0.0
      - rfc3987==1.3.8
      - rsa==4.6
      - sacred==0.8.1
      - seml==0.3.4
      - strict-rfc3339==0.7
      - tabulate==0.8.9
      - tensorboard==2.5.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.7.0
      - tensorflow==2.4.1
      - tensorflow-estimator==2.4.0
      - tensorflow-probability==0.12.2
      - termcolor==1.1.0
      - tinydb==4.3.0
      - tinydb-serialization==2.0.0
      - tqdm==4.50.2
      - webcolors==1.11.1
      - werkzeug==1.0.1
      - wrapt==1.12.1
