#!/bin/bash
#SBATCH --job-name=test
#SBATCH --output=job_output.txt
#SBATCH --error=job_error.txt
#SBATCH --ntasks=1
#SBATCH --time=10:00
#SBATCH --mem=100Gb

module load python/3.7
python3 train_and_eval.py with configs/gpn/new_classification_gpn_16.yaml data.dataset=CoraML