#!/bin/bash
#SBATCH --job-name=gpn-retrain
#SBATCH --output=job_output.txt
#SBATCH --error=job_error.txt
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6         # Ask for 6 CPUs
#SBATCH --gres=gpu:1              # Ask for 1 GPU
#SBATCH --mem=20G                 # Ask for 10 GB of RAM
#SBATCH --time=3:00:00            # The job will run for 10 minutes

module load python/3.7
virtualenv $HOME/rdp47
pip install torch==1.10.1
pip install -r req.txt
pip install torch-geometric
source $HOME/rdp47/bin/activate
python3 train_and_eval.py with configs/gpn/new_classification_gpn_16.yaml data.dataset=CoraML